build.gradle, src/main/java/org/researchspace/servlet/MProxyServlet.java
Fix depends on unreleased version of HTTP-proxy-Servlet, see fix here https://github.com/mitre/HTTP-Proxy-Servlet/pull/158.
Changes to build files are temporary to allow usage of locally build HTTP-proxy-Servlet dependency.
=> fixes #22. Don't url-decode URL path in MProxyServlet.

.eslintrc.js, src/main/web/components/forms/auto-form/FormGenerator.tsx, src/main/web/components/forms/inputs/FormSwitch.tsx
Circular dependencies were the cause of some issues with webpack build, where the same code was included many times into different bundles. Which sometime caused some weird bugs in semantic forms and knowledge maps.
Also along the way disable `no-use-before-define` in es-lint, it doesn't add any value because typescript is doing proper scope checking anyway.
=>  Remove circular dependencies in semantic-form component.

src/main/web/components/ui/template/TemplateItemComponent.ts
This is ugly hack to workaround issue with event propagation when react root is inside custom web component.
See https://github.com/facebook/react/issues/9242
This issue caused strange behavior of platform components inside semantic-map popovers and Mirador annotation popovers.
Basically even `semantic-link` was not working properly there and instead of changing the content of the page dynamically it reloaded the whole page.
Or for example it was not possible to use `mp-event-trigger` in such context.
=> Add workaround for the issue with react events inside web components.

src/main/java/org/researchspace/config/groups/EnvironmentConfiguration.java, src/main/web/app/app.ts
If needed it can still be set from the configuration.
=> Remove default session timeout.

src/main/resources/org/researchspace/apps/help/data/templates/http%3A%2F%2Fhelp.researchspace.org%2Fresource%2FPublishing.html, src/main/web/api/navigation/Navigation.ts
**Breaking Change**.
Make sure that with properly set `Default` namespace we can have resolvable IRIs even with nested context path without any redirects.
Example:
`Default = http://localhost:10214/resource/`.
Request `http://localhost:10214/resource/person/Bob`, will be actually resolved to `http://localhost:10214/resource/person/Bob` resource without any redirects.
Previously by default this request would be resolved to `http://localhost:10214/resource/Bob`. To resolve it to actual resource one would need to use `platformBaseIri` with `pathsToRewrite` configuration options to trigger redirects.
=> Properly resolve nested context path against Default namespace.

src/main/resources/org/researchspace/apps/help/data/templates/http%3A%2F%2Fhelp.researchspace.org%2Fresource%2FSemanticForm.html, src/main/web/api/sparql/SparqlUtil.ts, src/main/web/components/forms/FormModel.ts
Together with #65 this change helps to create forms that produce resolvable IRIs out of the box.
Also with relative `new-subject-template` form configuration can be easily made transferable between different deployments.
**Example.**
`Default = http://localhost:10214/resource/`. `semantic-form` with `new-subject-template='/person/{{UUID}}'` parameter, will create new resource with IRI like `http://localhost:10214/resource/person/123e4567-e89b-12d3-a456-426655440000`.
`{{FIELD_VALUE_LOCAL_NAME fieldName}}` placeholder allows to use field value local name.
Useful together with `type` field in auto-generated forms to create IRIs with type information.
**Example**
If we have a `type` field in the `semantic-form` and following `new-subject-template` configuration `/{{FIELD_VALUE_LOCAL_NAME …
=> semantic-form improvements.

src/main/resources/org/researchspace/apps/help/data/templates/http%3A%2F%2Fhelp.researchspace.org%2Fresource%2FSemanticQuery.html, src/main/resources/org/researchspace/apps/help/data/templates/http%3A%2F%2Fhelp.researchspace.org%2Fresource%2FSemanticTimeline.html, src/main/web/components/dashboard/DashboardItem.tsx, src/main/web/components/events/EventTargetTemplateRender.tsx, src/main/web/components/semantic/map/SemanticMap.ts, src/main/web/components/semantic/query/SemanticQuery.ts, src/main/web/components/semantic/table/SemanticTable.ts, src/main/web/components/semantic/table/Table.ts, src/main/web/components/semantic/tree/SemanticTree.ts, src/main/web/components/timeline/SemanticTimeline.tsx, src/main/web/components/ui/template/TemplateItem.ts
Previously many components that accept template as a parameter expected that the template should have a single root node.
That was because in React before v16 it was not possible to return array from render method.
But since React 16 it is now perfectly valid to do this.
Affects `semantic-table`, `semantic-query`, `semantic-tree`, `semantic-map`, `semantic-timeline`.
As an example see changes to `SemanticQuery` and `SemanticTimeline` help pages.
=> Change TemplateItem to properly work without a single root.

src/main/java/org/researchspace/services/storage/git/GitStorage.java
Quite convenient when developing templates locally and deploying on some remote server, to just restart platform instance on the server to get the latest changes.
=> Pull git storage on startup.

src/main/web/components/3-rd-party/ontodia/Ontodia.ts, src/main/web/components/3-rd-party/ontodia/authoring/FormBasedPersistence.ts, src/main/web/components/forms/persistence/PersistenceUtils.ts, src/main/web/components/forms/persistence/RawSparqlPersistence.ts, src/main/web/components/forms/persistence/SparqlPersistence.ts
Experimental support for `sparql` mode for `ontodia` authoring.
Also adds the ability to specify target named graph for all inserts or restrict all delete and insert operations to a specific named graph, for both `ontodia` and `semantic-form`
=> Experimental. Suport for target named graph in data authoring.

package-lock.json, package.json, src/main/web/lib/mirador/css/mirador.scss, src/main/web/ontodia/src/ontodia/viewUtils/toSvg.ts, webpack/webpack.config.js, webpack/webpack.prod.config.js
- Properly resolve images in css from mirador.
- Minify css in production build. 
- ontodia. On export to svg/png, don't fetch images from css that are already in data-url format.
=> css build and ontodia png/svg export fixes

src/main/java/org/researchspace/config/NamespaceRegistry.java, src/main/java/org/researchspace/rest/endpoint/SecurityEndpoint.java, src/main/java/org/researchspace/rest/endpoint/SetManagementEndpoint.java, src/main/java/org/researchspace/security/AnonymousUserFilter.java, src/main/java/org/researchspace/security/PlatformSecurityManager.java, src/main/resources/org/researchspace/apps/assets/config/shiro.ini, src/main/web/components/dashboard/DashboardComponent.tsx
Previously every browser session created new session for anonymous user. So number of active session was equal to number of people that accessed the platform.
This change make sure that we have only one internal session for anonymous user, so we don't even need to set cookies in case of anonymous access.
Also it adds additional user `anonymous-user`, that can have permissions different from the actual `anonymous` user, but will have the same user IRI. This user can be useful in situation where anonymous user is readonly and one needs somehow to populate clipboard or other resource for it.
=> Improve handling of anonymous user.

src/main/web/components/3-rd-party/ontodia/data/OntodiaDataProvider.ts
Only rdfs:label was applied in entity search, because it is hardcoded in the dataprovider profile. With this change we always set it to the value from UI config.
=> Use label properties from config in ontodia entity search.

src/main/web/ontodia/src/ontodia/data/sparql/sparqlDataProvider.ts
Before the fix order of instances was random. This change adds order by label, if label is not available then order by IRI.
=> Consistent orderding in the ontodia instance search panel.

src/main/web/widgets/ObjectRepresentationsWidget.ts
Before the fix images with relative URLs caused wrong calculation of modal dialog size and infinite loading spinner.
=> object-representation-widget. Fix loading of images with relative URL.

src/main/web/components/3-rd-party/ontodia/Ontodia.ts, src/main/web/components/3-rd-party/ontodia/Toolbar.tsx, src/main/web/components/3-rd-party/ontodia/authoring/FieldBasedValidationApi.ts, src/main/web/components/3-rd-party/ontodia/authoring/FieldConfigurationCommon.ts, src/main/web/components/3-rd-party/ontodia/authoring/OntodiaFieldConfiguration.ts, src/main/web/ontodia/src/ontodia/data/validationApi.ts, src/main/web/ontodia/src/ontodia/editor/validation.ts, src/main/web/ontodia/src/ontodia/workspace/toolbar.tsx, src/main/web/ontodia/src/ontodia/workspace/workspace.ts, src/main/web/schemas/FileInputConfig.json, src/main/web/schemas/ImageGraphAuthoringConfig.json, src/main/web/schemas/OntodiaConfig.json, src/main/web/schemas/OntodiaFieldConfigurationConfig.json, src/main/web/schemas/SplitPaneConfig.json
Added new property `enforce-constraints` to `ontodia-field-configuration` component. With this property set to true data change can't be saved before all validation errors are resolved.
=> Ability to enforce KPs constraints in Knowledge Map authoring mode.

.github/workflows/main.yml, build.gradle, bundle-config/RWStore.properties
so we can easily move blazegraph.jnl from local dev env do docker deployment and vice versa.
Also build zip distribution only for master.
=> dev env. Use the same blazegraph as in docker-compose.

src/main/web/components/forms/inputs/AutocompleteInput.tsx, src/main/web/components/forms/inputs/CompositeInput.ts, src/main/web/components/forms/inputs/NestedModalForm.tsx
semantic-form data was marked with DataState.Ready before all nested composite inputs were properly initialized, because of this it was not possible to use composite inputs in sparql persistence mode. In LDP mode the bug was visible only when some KPs created intermediate nodes with UUID (on every save new UUID was generated for intermediate nodes).
Also this change allows to edit resources in autocomplete input with nested forms. Previously it was only possible to create new resource with nested forms.
=> semantci-form. Fix initialization bug, allow to edit resources in autocomplete input.

src/main/web/components/forms/ValidationHelpers.ts, src/main/web/components/forms/inputs/TreePickerInput.tsx, src/main/web/components/forms/persistence/PersistenceUtils.ts, src/main/web/components/forms/persistence/RawSparqlPersistence.ts, src/main/web/components/semantic/lazy-tree/QueryDefaults.ts, src/main/web/components/semantic/lazy-tree/SemanticTreeInput.ts, src/main/web/styling/app/_form.scss
Add `orderByPattern` to influence a tree order, useful for periods or events.
```
<semantic-form-tree-picker-input for="broader"
tree-patterns='{"scheme": "{{scheme}}", "orderByPattern": "?item crm:P4_has_time-span/crm:P82a_begin_of_the_begin ?order"}'
></semantic-form-tree-picker-input>
```
=> Tree input. Ability to override tree-patterns from the Knowledge Pattern.

components.json, src/main/web/api/services/template/RemoteTemplateFetcher.ts, src/main/web/components/ui/template/InlineTemplate.ts
`inline-template` loads client side component specified in `template-iri`: 
```
<inline-template template-iri='{{resourceForm}}' 
options='{
"scheme": "...", 
"editable": "...",
}'>
</inline-template>
```
This is useful when actual template IRI is dynamic, stored in the database.
=> Add inline-template component that can be used to load dynamic client-side templates at runtime.

src/main/java/org/researchspace/config/groups/GlobalConfiguration.java, src/main/java/org/researchspace/data/rdf/container/LDPAssetsLoader.java
`forceLDPLoadFromStorages` config property can be used to force loading of LDP assets from the app. On restart, if LDP asset exist in the app, it will be deleted from the database and fully reloaded.
Here is our use-case for this feature. We have dev and prod deployment, they both have different runtime-storage, but share project app. 
We develop new functionality on dev and then when it is ready we can copy relevant templates and Knowledge Patterns to the project app, redeploy it on prod, and can be sure that all Knowledge Patterns are in sync with templates. 
=> Ability to force LDP assets loading from the app.

build.gradle, src/main/java/org/researchspace/repository/RepositoryManager.java
Also use custom build of gretty to make sure that in development mode ResearchSpace is started after blazegraph.
see https://github.com/gretty-gradle-plugin/gretty/pull/181
=> Don't start the platform until all repositories are reachable.

.github/workflows/main.yml
Currently we push `researchspace/platform-ci:latest` tag for master and `researchspace/platform-ci:DATE_GIT-HASH` for all other branches.
This change adds `researchspace/platform-ci:branch-name`, where branch-name is local part of the branch, e.g for build-docker/my-branch - researchspace/platform-ci:my-branch. It is useful to have for deployments that track some specific branch, to update such deployment one need to run:
```
docker-compose pull  
docker-compose up -d
```
without the need to know exact commit hash of the latest build.
=> Push stable docker tag for every branch.

src/main/java/org/researchspace/repository/RepositoryManager.java
Adding a simple control to prevent the sending of default test query for SailRepositories. 
For example, the SailRepository for Wikidata, and the upcoming for Geonames, are SailRepositories and both requires the queries to have mandatory identifiers.
When the test query is the following one (see the code below), a generic exception is raised.
https://github.com/researchspace/researchspace/blob/60233ec3181ff76c7dabb7a03a4e06b592db2166/src/main/java/org/researchspace/repository/RepositoryManager.java#L292-L314
=> Prevent default test query for SailRepositories

src/main/resources/org/researchspace/apps/default/config/page-layout/header.hbs, src/main/web/components/language-switch/UserLanguageSwitch.tsx
Possible languages can be set in the `ui.prop` config file, e.g:
```
preferredLanguages=en,fr,ara
```
Language selected by the user is stored in the user session.
Selected language is used only by components that use label service, like semantic-link, semantic-form input labels, etc.
=> Add language switch to default templates header.

src/main/java/org/researchspace/data/rdf/container/LDPAssetsLoader.java, src/main/java/org/researchspace/repository/MpRepositoryVocabulary.java, src/main/java/org/researchspace/repository/sparql/CustomSPARQLConnection.java, src/main/java/org/researchspace/repository/sparql/CustomSPARQLRepository.java, src/main/java/org/researchspace/repository/sparql/DefaultMpSPARQLRepositoryFactory.java, src/main/java/org/researchspace/repository/sparql/MpSPARQLRepositoryConfig.java, src/test/resources/org/researchspace/repository/test-sparql-basic-auth-repository.ttl, src/test/resources/org/researchspace/repository/test-sparql-digest-auth-repository.ttl
`mph:writable false` can be used to make connected repository a readonly one, e.g:
```
@prefix rep: <http://www.openrdf.org/config/repository#> .
@prefix sail: <http://www.openrdf.org/config/sail#> .
@prefix sr: <http://www.openrdf.org/config/repository/sail#> .
@prefix sparqlr: <http://www.openrdf.org/config/repository/sparql#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix mph: <http://www.researchspace.org/resource/system/repository#> .
[] a rep:Repository ;
rep:repositoryID "default" ;
rdfs:label "default" ;
rep:repositoryImpl [
rep:repositoryType "researchspace:SPARQLBasicAuthRepository" ;
sparqlr:query-endpoint <http://localhost:10216/sparql> ;
mph:writable false ;
mph:username "user" ;
mph:password "password"
].
```
Useful when connecting to existing repository …
=> Ability to connect to sparql repository in readonly mode.

src/main/java/org/researchspace/services/storage/git/GitStorage.java
Quite convenient when setting up new installation, so one doesn't need to to manually clone git repo first.
Also can be used for demo setups, one can simply provide docker compose with configured git runtime readonly storage pointing to publicly available github repository with demo app, e.g:
```
-Dconfig.storage.test.type=git
-Dconfig.storage.test.mutable=false
-Dconfig.storage.test.localPath=/git-clone-app
-Dconfig.storage.test.remoteUrl=https://github.com/somerepo",
-Dconfig.storage.test.branch=master
```
for private repositories one should provide remoteUrl in the following format `git@github.com:somerepo.git`, and repository credentials will be picked up from the `~/.ssh`.
=> git storage. Clone git repository if it is not already present.

src/main/web/components/semantic/search/config/SearchConfig.ts, src/main/web/components/semantic/search/web-components/SemanticSearch.ts
Previously search component, by default, is geting initial value from `?semanticSearch` url queury param, now one can use explicit parameter to provide initial value:
```
<semantic-query
query='SELECT ?searchStructure { ?? Platform:searchState ?searchStructure }'
template='{{> template}}'
>
<template id='template'>
<semantic-search ... initial-state='{{bindings.0.searchStructure.value}}'></semantic-search>
</template>
</semantic-query>
```
=> Add parameter to specify initial state for semantic-search.

src/main/java/org/researchspace/config/NamespaceRegistry.java, src/test/java/org/researchspace/config/NamespaceRegistryTest.java
In SPARQL grammar it is valid to have colon symbol in the local name of prefixed IRI, e.g if we have `prefix example: <http://example.com/>`, it is valid to have IRI `example:something:SomethingElse` that will be resolved to `<http://example.com/something:SomethingElse>`, when such prefixed IRI was used as a template IRI it was incorrectly resolved by TemplateService.
=> Fix prefixed IRI resolution in TemplateService when local name contains ":" symbol.

src/main/java/org/researchspace/services/storage/git/GitStorage.java
In jGit default clone fetches only master, we need to manually specify the branch from the config.
=> Git storage. Set branch when clonning repository.

src/main/web/components/timeline/SemanticTimeline.tsx
group template in semantic-timeline config was simply ignored, because of some inconsistencies in vis.js timeline API. 
with the fix, template from `  options='{ "groupTemplate":"{{> groupTemplate}}" }'` is now properly applied:
=> bugfix. semantic-timeline. Group template was not properly applied.

src/main/web/components/semantic/search/web-components/SemanticSearchResult.tsx
This is the fix that @aindlq provided for the semantic-search-result-context component. We were having problems getting the component to load properly in the search results template.
=> Fixed semantic search result context bug

src/main/java/org/researchspace/cache/ResourcePropertyCache.java, src/test/java/org/researchspace/cache/LabelCacheTest.java
move VALUES clause to the root of labels/thumbnails query.
previously VALUES clause was inserted into every UNION, but it seems that blazegraph ASTStaticBindingsOptimizer was not able to properly pick them up as a result it always applied them in the end, that lead to very heavy queries.
=> blazegraph optimization for labels/thumbnail service

src/main/web/api/services/template/functions/StringsFunctions.ts
Adds a split helper to the frontend handlebars template.
Usage:
```html
<ul>
{{#each split ("list of values") }}
<li>{{this}}</li>
{{/each}}
</ul>
```
```html
<ul>
{{#each split("list;of;values" ";" }}
<li>{{this}}</li>
{{/each}}
</ul>
```
Both examples produce:
<ul>
<li>list</li>
<li>of</li>
<li>values</li>
</ul>
=> Add split helper

.github/pull_request_template.md, src/main/web/components/forms/forms.scss, src/main/web/components/forms/inputs/TreePickerInput.tsx, src/main/web/components/semantic/lazy-tree/SemanticTreeInput.ts, src/main/web/components/semantic/lazy-tree/SparqlNodeModel.ts
The semantic-form-tree-picker-input in forms allows to render a dropdown where the user can select terms from a vocabulary (called 'scheme') structured as a tree.
The current version of the semantic-form-tree-picker-input has:
-  'tree-patterns' to specify the scheme details;
-  'nested-form-template' to display a button (New) that opens a modal where the user can create a new term in the vocabulary.
An update of the Semantic Tree Input is requested for the following actions:
- allow the user to easily open the entire Vocabulary in a new frame;
- allow an easy customisation of the term labels when displayed in the vocabulary list or in the selected term.
```
<semantic-form-tree-picker-input 
for='type' 
label="Type" 
placeholder="Select type"
close-dropdown-on-selection='false' …
```
=> semantic-form-tree-picker-input

src/main/java/org/researchspace/secrets/AbstractSecretResolver.java, src/main/java/org/researchspace/secrets/EnvironmentSecretResolver.java, src/test/java/org/researchspace/secrets/SecretsTest.java
Secrets from the Java Environment would not be mapped when initialising repositories.
There were a few lines of code to close #282.
Two Java classes have been modified. 
**AbstractSecretResolver** removes unexpected characters and transforms to lowercase the key to access secrets (e.g., what comes after "secret.")
**EnvironmentSecretResolver** detects when a secret starts with "secret" and returns the key.
There are no UI changes.
The decision was to prepend "secret." to the secret variable name, as described in the RS documentation.
I have integrated the unit test in **SecretsTest.java**. 
But also, creating a repository with a username and password pair is necessary to test. Then, try a federated query against that repository using ephedra. 
This is similar to something we use for the …
=> Add secrets from environment + unit test

src/main/java/org/researchspace/data/rdf/container/LDPAssetsLoader.java, src/main/java/org/researchspace/repository/MpRepositoryVocabulary.java, src/main/java/org/researchspace/repository/RepositoryManager.java, src/main/java/org/researchspace/repository/sparql/CustomSPARQLConnection.java, src/main/java/org/researchspace/repository/sparql/CustomSPARQLRepository.java, src/main/java/org/researchspace/repository/sparql/DefaultMpSPARQLRepositoryFactory.java, src/main/java/org/researchspace/repository/sparql/MpSPARQLRepositoryConfig.java, src/test/java/org/researchspace/repository/SPARQLDigestAuthRepositoryConfigTest.java, src/test/resources/org/researchspace/repository/test-sparql-basic-auth-repository.ttl, src/test/resources/org/researchspace/repository/test-sparql-digest-auth-repository.ttl
Some RDF databases, like https://github.com/oxigraph/oxigraph return error if one tries to clear graph that doesn't exist. That is acceptable behavior according to standard. 
This change introduce new repository config property `silentMode`. When the value is true, RDF4J will generate `CLEAR SILENT GRAPH` instead of `CLEAR GRAPH` that is generated by default. `silentMode` is false by default and need to be explicitly enabled in the repository config. So it is non breaking change and should not have any side effect.
```
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sparql: <http://www.openrdf.org/config/repository/sparql#> .
@prefix rep: <http://www.openrdf.org/config/repository#> .
@prefix sail: <http://www.openrdf.org/config/sail#> .
@prefix sr: …
```
=> oxigraph. Ability to enable silent mode for repository.

build.gradle
buildZip produced broken bundle because of bug in gretty.
see https://github.com/gretty-gradle-plugin/gretty/pull/314
=> Update gretty to fix problem with buildZip.

src/main/web/styling/_variables.scss
Use the same variable for `lg` and `xs` inputs.
I also removed `input-border-radius` where it was set to 0, it was confusing because later it was overridden with 2.
Just add some form to the template and check if input has correct border-radius:
```
<form>
<div class="form-group form-group-lg">
<input
required
class="form-control"
placeholder="Search"
type="search"
name="keyword"
/>
</div>
</form>
```
=> Use `--input-border-radius` for large and small inputs.

src/main/web/api/navigation/Navigation.ts, src/main/web/api/services/config-holder.ts
Even when system is configured to have resolvable URIs semantic-link and other components that used internal navigation still generated URL with ?uri or prefixes.
For example in PHAROS URL like https://artresearch.net/resource/zeri/work/99999 was successfully resolved to a proper resource when navigation from a browser directly, but when the same URI was used in semantic link one would  see ugly URL like `https://artresearch.net/resource/?uri=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fwork%2F99999`
Requires `platformBaseIri` to be set in environment config.
If testing on localhost:
1) set `platformBaseIri=http://localhost:10214` in the `environment.prop`
2) change default namespace to `Default = http://localhost:10214/resource/` in the `namespaces.prop`
3) then create a test page …
=> Prefer compact URL for resolvable URIs in resource navigation.

src/main/java/org/researchspace/cache/LabelCache.java, src/main/java/org/researchspace/cache/ResourcePropertyCache.java, src/main/java/org/researchspace/config/groups/EnvironmentConfiguration.java, src/main/resources/org/researchspace/apps/help/data/templates/http%3A%2F%2Fhelp.researchspace.org%2Fresource%2FBasicSystemConfiguration.html
1) Adds ability to increase labels cache size.
2) Ability to disable batched labels requests. When using RS with QLever it is much better to send one big request than many small ones. So by setting `labelsBatchSize` to something big like `100000` we can effectively disable batching.
3) Disable time based cache invalidation.
Also updated configuration help page.
Added `labelsCacheSize` and `labelsBatchSize` to `enivronment.prop` config.
I guess we can enable/dissable some optimizations based on type of repository used. E.g for qlever labels batching doesn't make any sense because it can deal with huge requests much better than blazegraph.
=> Configurable label cache.

src/main/resources/org/researchspace/apps/default/data/templates/http%3A%2F%2Fwww.researchspace.org%2Fresource%2FResourceCardTemplate.html, src/main/resources/org/researchspace/apps/default/data/templates/http%3A%2F%2Fwww.researchspace.org%2Fresource%2FSemanticNarrativeTemplate.html, src/main/web/styling/_card.scss
The icon ares in the Resource card wasn't resizing properly when autosize=true
Currently this is used only in semantic narrative card
Added the new css class resource-card__media-container-autosize
=> Created new css class for card when autosize=true

src/main/resources/org/researchspace/apps/default/data/templates/http%3A%2F%2Fwww.researchspace.org%2Fresource%2FAuthorityDocumentSystem.html
The form available to edit System authority documents doesn't display the existing values.
KPs have been changed in the main form, but the edit form wasn't updated with the same KPs. Now this has been fixed.
System authority documents - edit form
=> System authority documents - fix on edit form KPs

src/main/java/org/researchspace/templates/TemplateByIriLoader.java, src/main/java/org/researchspace/templates/TemplateIriUtils.java, src/main/java/org/researchspace/templates/TemplateResolver.java, src/test/java/org/researchspace/templates/TemplateByIriLoaderTest.java, src/test/java/org/researchspace/templates/TemplateIriUtilsTest.java, src/test/java/org/researchspace/templates/TemplateResolverTest.java
The existing template resolution system was limited to storing templates with URL-encoded filenames in specific directory structures, making template organization inflexible and filenames unreadable. 
Also, this is the new implementation of #252, which is now compatible with RS version 4.x
This PR implements a template resolution system in which:
- TemplateResolver class handles all filename typologies: full IRIs (`http%3A%2F%2Ftest.org%2Fresource%2FPerson.html`), prefixed forms `test:Person`, and `Template:{prefix}:{name}`
- Template files can be stored in any folder structure independent of the IRI hierarchy
- The new system employs a fallback mechanism to conduct comprehensive searches across all template directories when the direct lookup fails, ensuring retro compatibility and …
=> implement hierarchical templating system

blazegraph-vocabularies/build.gradle, build.gradle
Add blazegraph war to the source tree. Fixes #415.
Sonatype repository reached end of life, see https://central.sonatype.org/news/20250326_ossrh_sunset/
Added dependency directly to the source tree.
```
./gradlew runAll
```
=> Add blazegraph war to the source tree.

src/main/resources/org/researchspace/apps/default/data/templates/http%3A%2F%2Fwww.researchspace.org%2Fresource%2Fsystem%2Fforms%2FDimension.html, src/main/resources/org/researchspace/apps/default/data/templates/http%3A%2F%2Fwww.researchspace.org%2Fresource%2Fsystem%2Fforms%2FMonetaryAmount.html, src/main/resources/org/researchspace/apps/default/ldp/configurations/http%3A%2F%2Fwww.researchspace.org%2Fpatterns%2Fsystem.trig, src/main/resources/org/researchspace/apps/default/ldp/system/http%3A%2F%2Fwww.researchspace.org%2Fpattern%2Fsystem%2Fdimension%2Flower_value.trig, src/main/resources/org/researchspace/apps/default/ldp/system/http%3A%2F%2Fwww.researchspace.org%2Fpattern%2Fsystem%2Fdimension%2Fupper_value.trig, src/main/resources/org/researchspace/apps/default/ldp/system/http%3A%2F%2Fwww.researchspace.org%2Fpattern%2Fsystem%2Fdimension%2Fvalue.trig, src/main/resources/org/researchspace/apps/default/ldp/system/http%3A%2F%2Fwww.researchspace.org%2Fpattern%2Fsystem%2Fdimension%2Fvalue_decimal.trig, src/main/resources/org/researchspace/apps/default/ldp/system/http%3A%2F%2Fwww.researchspace.org%2Fpattern%2Fsystem%2Fdimension%2Fvalue_integer.trig
KP dimension_value="http://www.researchspace.org/pattern/system/dimension/value" must be restricted to select only values of datatype string.
The ability to record a dimension value as integer or decimal has been requested in projects, especially in scientific dataset contexts.
- Fix on dimension_value (xsd:string) KP
- Added Dimension value as integer and decimal value in Dimension and Monetary amount forms
=> Dimension value KP fix
