researchspace/researchspace

build.bat
build.sh
metaphacts-platform/web/.npmrc
metaphacts-platform/web/yarn.lock
project/plugins.sbt
project/repositories
project/webpack/.npmrc
project/webpack/yarn.lock
researchspace/web/.npmrc
researchspace/web/yarn.lock

Switch to public repositiores instead of nexus.grapphs.com proxy.

Use public npm and maven repositories

---

src/main/java/org/researchspace/services/fields/FieldsBasedSearch.java

**Breaking Change**
Changes the way how `[[searchConfigForFields]]` and `[[searchConfigForFieldsFromQuery]]` handlebars functions are generating search configuration from field definitions.
Before this change "insert pattern" from field definition was used to generate query pattern for search configuration.
Probably there was a good reason to use insert instead of select. But from our experience it caused so much confusion and inconvenience that it worth to do a breaking change and switch to "select pattern".
Also it enables searches with field definitions that have normal insert pattern but very sophisticated select pattern (with sub-queries, etc.).

Use select pattern for search config generation.

---

build.gradle
src/main/java/org/eclipse/rdf4j/query/parser/sparql/MpTupleExprBuilder.java
src/main/java/org/researchspace/repository/sparql/CustomSPARQLRepository.java
src/main/java/org/researchspace/repository/sparql/DefaultMpSPARQLRepositoryFactory.java
src/main/java/org/researchspace/repository/sparql/SPARQLAuthenticatingRepository.java
src/main/java/org/researchspace/templates/helper/JsonFromSparqlSelectSource.java
src/test/java/org/researchspace/sparql/renderer/MpSparqlQueryRendererTest.java
src/test/java/org/researchspace/sparql/renderer/MpTestTupleExprOptimizer.java

Update java dependencies:
- gretty - fix for product builds, so now we can finally use gretty product build to create zip distribution
- handlebars.java - fix some edge cases with inline partials
- rdf4j - enable incredibly nice passthrough performance improvement, see eclipse/rdf4j#400

Update dependencies. Enable perf improvement in rdf4j.

---

build.gradle
src/main/java/org/researchspace/config/Configuration.java
src/main/java/org/researchspace/di/MainGuiceModule.java
src/main/java/org/researchspace/services/storage/MainPlatformStorage.java
src/main/java/org/researchspace/services/storage/api/StorageConfigLoader.java
src/main/java/org/researchspace/ui/templates/MainTemplate.java
src/main/resources/org/researchspace/apps/internalStorageDev.prop

Fix default apps ordering issue in dev build.

---

.github/workflows/main.yml
build.gradle
gradle.properties

* Tag builds from master with `:latest` tag.
* Set more meaningfull version.

Build master on PR merge.

---

.github/workflows/main.yml

Fix typo in github actions build for master.

---

src/main/java/org/researchspace/data/rdf/RioUtils.java
src/main/java/org/researchspace/servlet/SparqlServlet.java

* in SparqlServlet for construct/describe queries
* in LDP container export

Add namespaces on RDF export.

---

src/main/web/components/dashboard/DashboardItem.tsx

Thinking Frames. Don't show intermediate screen for noResource frames.

---

src/main/web/api/services/template/functions/GenericFunctions.ts
src/main/web/components/iiif/mirador/Mirador.ts
typings/mirador/mirador.d.ts

Mirador crashes when many instances of it are initialized on the same page.

---

src/main/web/components/forms/inputs/AutocompleteInput.tsx
src/main/web/components/ui/inputs/AutoCompletionInput.ts

semantic-form. Enable drag and drop into autocomplete input from clipboard.

---

src/main/resources/org/researchspace/apps/system/data/templates/Template%3Ahttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23Class.html
src/main/resources/org/researchspace/apps/system/data/templates/Template%3Ahttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23Resource.html

Fix error in rdfs:Resource and owl:Class templates.

---

src/main/web/components/forms/FieldBasedVisualization.ts
src/main/web/components/forms/QueryValues.ts

Useful when we want to fetch values for additional IRIs like owl:sameAs or skos:exactMatch.
Example:
```
<mp-field-visualization subject='[[this]]' additional-subjects='[[jsonArrayFromSelect (setQueryBindings "SELECT ?s WHERE { ?s owl:sameAs ?resource }" resource=this.iri)]]'                                         
...
</mp-field-visualization>
```
As result field select query will be parametrized with VALUES clause that includes original subject as well as additional subjects:
```
SELECT ?value ?label  WHERE {
VALUES (?subject) {
(<https://pharos.artresearch.net/resource/villaitatti/work/8000845372>)
(<https://pharos.artresearch.net/resource/villaitatti/work/8000851519>)
(<https://pharos.artresearch.net/resource/work/1589125793>)
}
?subject crm:P43_has_dimension ?dimension.
?dimension …
```

Fixes #76. Additional subjects for mp-field-visualization component.

---

README.md

Add zip download link that can be used without github login.

Add download links to readme.

---

.gitignore
src/main/java/org/researchspace/repository/MpRepositoryVocabulary.java
src/main/java/org/researchspace/rest/filters/RequestRateLimitFilter.java
src/main/java/org/researchspace/rest/filters/UserAgentFilter.java
src/main/java/org/researchspace/sail/rest/AbstractRESTWrappingSailConnection.java
src/main/java/org/researchspace/sail/rest/AbstractServiceWrappingSail.java
src/main/java/org/researchspace/sail/rest/AbstractServiceWrappingSailConfig.java
src/main/java/org/researchspace/sail/rest/AbstractServiceWrappingSailConnection.java
src/main/java/org/researchspace/sail/rest/RESTSail.java
src/main/java/org/researchspace/sail/rest/RESTSailConfig.java
src/main/java/org/researchspace/sail/rest/RESTSailConnection.java
src/main/java/org/researchspace/sail/rest/RESTSailFactory.java
src/main/java/org/researchspace/sail/rest/openstreetmap/OpenstreetmapSail.java
src/main/java/org/researchspace/sail/rest/openstreetmap/OpenstreetmapSailConfig.java
src/main/java/org/researchspace/sail/rest/openstreetmap/OpenstreetmapSailConnection.java
src/main/java/org/researchspace/sail/rest/openstreetmap/OpenstreetmapSailFactory.java
src/main/java/org/researchspace/sail/rest/wikidata/WikidataSail.java
src/main/java/org/researchspace/sail/rest/wikidata/WikidataSailConnection.java
src/main/resources/META-INF/services/org.eclipse.rdf4j.sail.config.SailFactory
src/main/resources/org/researchspace/apps/default/config/repository-templates/openstreetmaps.ttl
src/main/resources/org/researchspace/apps/help/data/templates/http%3A%2F%2Fhelp.researchspace.org%2Fresource%2FOpenStreetMap.html
src/main/resources/org/researchspace/apps/help/data/templates/http%3A%2F%2Fhelp.researchspace.org%2Fresource%2FRESTSail.html
src/main/resources/org/researchspace/apps/help/data/templates/http%3A%2F%2Fhelp.researchspace.org%2Fresource%2FStart.html

This pull request contains the java code to execute and run OpenStreetMap federation. It comes with its own documentation page.  The OSM federation integration is completely encoded within the source files.
It contains also a starting RESTSail federation integration, which is a general federation to handle any type of REST request. Its documentation is still under development.
Right now, RESTSail only handles GET and POST methods and it is able to parse only JSON responses.

OSM (hardcoded) + REST Sail 

---

src/main/java/org/researchspace/data/rdf/container/AbstractLDPResource.java
src/main/java/org/researchspace/rest/endpoint/TemplateEndpoint.java
src/main/java/org/researchspace/services/storage/MainPlatformStorage.java
src/main/java/org/researchspace/services/storage/StorageUtils.java

Username was not properly resolved in case of SSO.

SSO. Properly resolve username when creating storage object metadata.

---

src/main/java/org/researchspace/config/groups/EnvironmentConfiguration.java
src/main/java/org/researchspace/security/ShiroGuiceModule.java
src/main/java/org/researchspace/security/sso/SSOCallbackFilter.java
src/main/java/org/researchspace/security/sso/SSOLoginFilter.java

@aindlq These are the changes we discussed. We decided to fully disable the default login page and replace it with keycloak (for our use case this is best, we don't want users finding the default login page at all). Let me know if there's anything that is going to be changed!

Added anonymous users for the keycloak sso

---

build.gradle
src/main/java/org/researchspace/services/storage/s3/S3Storage.java
src/main/java/org/researchspace/services/storage/s3/S3StorageConfig.java
src/main/java/org/researchspace/services/storage/s3/S3StorageFactory.java
src/main/resources/META-INF/services/org.researchspace.services.storage.api.StorageFactory
src/main/resources/org/researchspace/apps/help/data/templates/http%3A%2F%2Fhelp.researchspace.org%2Fresource%2FStorage.html

The PR has been changed and moved after a cherry-pick from #207

S3 basic implementation with AWS SDK 1.x (version 2)

---

.github/workflows/pull_request_template.md

Added template to document a pull request

added pull_request_template

---

src/main/web/components/forms/index.ts
src/main/web/components/forms/inputs/index.ts
webpack/webpack.config.js

I need more exported Components for my external modules.
More exports in index.ts and additional packages in webpack.config.js

add more component exports for modules.

---

src/main/resources/org/researchspace/apps/help/data/templates/http%3A%2F%2Fhelp.researchspace.org%2Fresource%2FStart.html
src/main/web/components/3-rd-party/ontodia/DiagramSearchResult.tsx
src/main/web/components/semantic/search/data/search/Model.ts
src/main/web/components/semantic/search/data/search/Serialization.ts
src/main/web/components/semantic/search/web-components/SemanticSearch.ts
src/main/web/components/semantic/search/web-components/SemanticSearchApi.ts
src/main/web/components/semantic/search/web-components/SemanticSearchTableResult.tsx

Remove all references to graphscope

Cleanup some unused code.

---

src/main/java/org/researchspace/security/CustomWebSubjectFactory.java
src/main/java/org/researchspace/security/sso/ShiroProfileManagerFactory.java
src/main/resources/org/researchspace/security/sso/shiro-sso-keycloak-default.ini
src/main/resources/org/researchspace/security/sso/shiro-sso-oidc-default.ini
src/main/resources/org/researchspace/security/sso/shiro-sso-saml2-default.ini

There was a regression in SSO functionality.
With the newer version of pac4j one need to manually initialize special subject factory that bridges pac4j and shiro.

SSO regression fix.
